export const SET_ERRORS = 'SET_ERRORS';
export const SET_LOADING_ALERT = 'SET_LOADING_ALERT';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE';
